### ISSUE TITLE
Metaphor Image ?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-phoenix-framework#11]
You can _attempt_ to make a "_slow car_" go faster ...

![car-mod-fail](https://cloud.githubusercontent.com/assets/194400/22628288/41afc3d0-ebc9-11e6-98f3-67a1bc3a1411.png)
<small> See more at: http://www.ridelust.com/30-custom-cars-from-around-the-world 
and http://www.bobatoo.co.uk/blog/the-10-worst-car-modifications-ever/</small> 🤣 

***Or***... just buy the car that was built for speed, safety and environmental friendliness and stop wasting your time on the past!

![model-s-photo](https://cloud.githubusercontent.com/assets/194400/22628333/e8a107ee-ebc9-11e6-9140-6be11cdddd87.jpg)

**Comment by Jbarget** [comment]
can this be closed?

**Comment by nelsonic** [comment]
@Jbarget yeah, it _can_.
I'm still in "_hope_" that someone `else` will suggest a _bettererere_ metaphor. 
(_or just remove the car refs which might not appeal to everyone..._)
Closing. ✅
