### ISSUE TITLE
Phoenix Programming Book Available Online "Free" ?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-phoenix-framework#110]
Let me `start` by saying that if you have income/means and can _afford_ to _pay_ for the Phoenix Book, 
please _buy_ it to _support_ the authors 
so they will `continue` to make great content 
(_and be able to work on the Phoenix framework!_)
The book is _excellent_ and is _easily_/_still_ the ***best way to learn Phoenix***!
We _purchased_ paper copies of the book for all members of our team
see: https://github.com/dwyl/learn-elixir/issues/11
and _highly_ recommend _everyone_ read it and work through the examples 
as the _fastest_ way to learn Phoenix.

While searching for how to do something with Phoenix Channels ***Google*** served me this result:
![searching-for-unmatched-topic-shows-phoenix-book](https://user-images.githubusercontent.com/194400/34874165-d01db7f8-f78f-11e7-9aae-05a240cf07e6.png)
Which I clicked on in the _hope_ that it would have something _useful_/_relevant_:
http://xzlearning.com/skills/5227
![image](https://user-images.githubusercontent.com/194400/34872066-8037648a-f787-11e7-90d6-d40d6a6c139f.png)
It did not actually _solve_ my _specific_ Channels issue, 
which I've opened a separate question for:https://github.com/dwyl/learn-phoenix-framework/issues/109

But ...
I _recognised_ the copy from having read Chris Mccord's book while learning Phoenix ... 
and sure enough, the _entire_ content of the book is there on this Chinese "Learning" Website:
http://xzlearning.com/transfer_models/587
![image](https://user-images.githubusercontent.com/194400/34872093-8f07caa4-f787-11e7-960e-45c934f432cf.png)

It appears that the ***PDF Version*** of the book is _also_ available with a _simple **Google search**_ (_despite the content of the book having a clear copyright notice which Google's bots can **definitely** "read" and know **not** to index!_):
https://www.google.co.uk/search?q=phoenix+programming+book+pdf
![image](https://user-images.githubusercontent.com/194400/34871918-1f85b006-f787-11e7-88f4-2cfa8edb3211.png)
This time on a Russian Website:
http://www.r-5.org/files/books/computers/languages/ruby/rb-way/Chris_McCord_Bruce_Tate_Jose_Valim-Programming_Phoenix-EN.pdf 
![image](https://user-images.githubusercontent.com/194400/34872035-6e191b72-f787-11e7-9886-0cc070ad5240.png)

I'm _conflicted_ about sharing this, as it's (_probably_) "copyright infringement" 
for these website to host the _full_ content of the book ... 🤔 
But at the _same_ time I feel the _more_ people in the community 
who are able to learn Phoenix from the _best_ available source, the better for the _ecosystem_.

**Comment by nelsonic** [comment]
This is an issue for the content creators/owners to resolve. closing.

**Comment by zzz6519003** [comment]
from third world
