### ISSUE TITLE
Should we be using brunch in our apps

### ISSUE THREAD

**Issue by samhstn** [dwyl/learn-phoenix-framework#111]
Phoenix comes quite nicely set up with brunch, but it may be overkill, more work to configure and giving us less control over our static assets.

Another option is to instead set up our development server to watch `npm` commands instead of the default `brunch` stuff which ends up in our `config/dev.exs`.

When building for the `prod` environment we would have more control over how our static assets are built. This would require more work, but should be easier to debug and optimise.

**Comment by nelsonic** [comment]
@shouston3 yeah, I was thinking the same thing the other day, _might_ Brunch be "too much". 
What is the most "_basic_" way of compiling an Elm app for use with a Phoenix backend?

**Comment by shouston3** [comment]
Most basic in terms of quick start is just the default brunch configuration.

Most basic in terms of least technologies would be something like:
```sh
node_modules/.bin/elm make Main.elm --output $PATH_TO_PHX_WEB_DIR/priv/static/js/app.js
```

**Comment by nelsonic** [comment]
@shouston3 will that "_live/hot reload_" the `app.js` in the Browser?

**Comment by shouston3** [comment]
That command alone won't, but all you need to do from there add an `npm` command to do the above, then edit your `config/dev.exs` file run that command, something like:

```elixir
...
check_origin: false,
watchers = [{:npm, ["run", "watch:elm", cd: Path.expand("../assets", __DIR__)]}]
```

**Comment by shouston3** [comment]
I have a working version here: https://github.com/shouston3/pete_boilerplate/tree/master/pete_auth

**Comment by nelsonic** [comment]
Thanks for adding link @shouston3, will take a look at it. 👍

**Comment by nelsonic** [comment]
GOTO: #118 (_Phoenix 1.4 Uses Webpack so Brunch is no longer a "question" for new users. closing_)
