### ISSUE TITLE
Great Resource

### ISSUE THREAD

**Issue by njwest** [dwyl/learn-phoenix-framework#112]
Hey ya'll, just wanted to leave a note -- I think this is a phenomenal learning resource and I am quite thankful that you all put it up here!

Would be great to see it updated for Phoenix 1.3+

Also, some of the examples are incomplete (missing schema/changeset functions referenced in controller code). If this project is ever resurrected and updated to Phoenix 1.3, consider filling in the gaps

Thanks again!

**Comment by nelsonic** [comment]
@njwest thanks for the note. 👍 
have you seen: https://github.com/dwyl/phoenix-chat-example ? 💭
