### ISSUE TITLE
Could not find "rebar3", which is needed to build dependency :ranch

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-phoenix-framework#121]
When following the **Programming Phoenix 1.4 Book** "Create a **Throwaway Project**" (page 19),
(_which is the same as the "**hello world**" app in the "Up and Running":
https://hexdocs.pm/phoenix/up_and_running.html#content that **everyone** should follow_)
```
mix ecto.create
```

But saw the following output:
```
17:45:43.249 [info]  Compiling file system watcher for Mac...
mix
17:45:44.671 [info]  Done.
==> file_system
Compiling 7 files (.ex)
Generated file_system app
==> connection
Compiling 1 file (.ex)
Generated connection app
==> gettext
Compiling 1 file (.yrl)
Compiling 1 file (.erl)
Compiling 20 files (.ex)
Generated gettext app
==> hello
Could not find "rebar3", which is needed to build dependency :ranch
I can install a local copy which is just used by Mix
Shall I install rebar3? (if running non-interactively, use "mix local.rebar --force") [Yn] y
** (Mix) Could not find "rebar3" to compile dependency :ranch, please ensure "rebar3" is available
```
![image](https://user-images.githubusercontent.com/194400/50524541-34fc4700-0ace-11e9-94e4-02524d21c24c.png)

> **Note**: I'm following the "Hello World" example on a "New" Mac 💻 and seeing where the "gaps" are in my stack ahead of writing a new tutorial for the new year. Just wanted to _capture_ this error message and the corresponding solution (_see below_) in case anyone else faces the same issue.

**Comment by nelsonic** [comment]
Ok ... it was PEBKAC ... I skipped a step! When the installer asks:
```
Fetch and install dependencies? [Yn] y
```
I hastily hit the `[Enter]` key instead of the `y` key ... so the dependencies were not installed correctly.

Run the following in order:
```sh
cd hello
mix deps.get
cd assets && npm install && node node_modules/webpack/bin/webpack.js --mode development
cd ..
```
Then when you run `mix ecto.create` it will work. 
![image](https://user-images.githubusercontent.com/194400/50524810-bf917600-0acf-11e9-9150-f76d8be7fcd9.png)

```
mix phx.server
```
![image](https://user-images.githubusercontent.com/194400/50524821-db951780-0acf-11e9-972b-0040fae6b7d5.png)

Works: http://localhost:4000
![image](https://user-images.githubusercontent.com/194400/50524849-fcf60380-0acf-11e9-9170-72c1ee329c05.png)

This thread: https://github.com/phoenixframework/phoenix/issues/842 included the error message but not the _solution_ ... 
If you face this issue, just re-trace your steps and it will work.
If not, comment in this thread and we will help you!

**Comment by jupmorenor** [comment]
I had the same issue while CI GitLab runner execution.
It is solved using the suggestion given:
Add mix local.rebar --force before running mix ecto.create
