### ISSUE TITLE
Phoenix 1.7 RC

### ISSUE THREAD

**Issue by SimonLab** [dwyl/learn-phoenix-framework#152]
![image](https://user-images.githubusercontent.com/6057298/200823480-849c6e3e-cdb9-49a6-bb06-034f68d1823a.png)

Continue reading at:
https://phoenixframework.org/blog/phoenix-1.7-released

**Comment by nelsonic** [comment]
Wish the `~p` [sigil](https://elixir-lang.org/getting-started/sigils.html) (🤷‍♂️) was a more intuitive alphabet character like `~v` (verified route) ...
Reading: Upgrading from Phoenix v1.6.x to v1.7.0 https://gist.github.com/chrismccord/00a6ea2a96bc57df0cce526bd20af8a7 seems pretty straightforward.

**Comment by nelsonic** [comment]
See: https://github.com/dwyl/phoenix-chat-example/pull/152

**Comment by nelsonic** [comment]
https://phoenixframework.org/blog/phoenix-1.7-final-released
