### ISSUE TITLE
Cannot push to learn-phoenix repo

### ISSUE THREAD

**Issue by JMurphyWeb** [dwyl/learn-phoenix-framework#19]
@nelsonic I don't have permissions to push to this repo:

```
remote: Permission to dwyl/learn-phoenix-framework.git denied to JMurphyWeb.
fatal: unable to access 'https://github.com/dwyl/learn-phoenix-framework.git/': The requested URL returned error: 403
```

**Comment by RobStallion** [comment]
@nelsonic. Would you be able to give me those same permissions please. Thanks

**Comment by iteles** [comment]
@JMurphyWeb @RobStallion 

Granted, but **please _please_ make sure you're following the dwyl process** in our contributing guide _to the letter_! https://github.com/dwyl/contributing 🙏

**Comment by JMurphyWeb** [comment]
OK @iteles Thanks!

**Comment by nelsonic** [comment]
@JMurphyWeb is this _still_ an issue or can it be closed? 🤔

**Comment by JMurphyWeb** [comment]
Closed
