### ISSUE TITLE
Heroku deployment documentation images

### ISSUE THREAD

**Issue by jruts** [dwyl/learn-phoenix-framework#24]
Images for https://github.com/dwyl/learn-phoenix-framework/pull/23 .

![add_buildpack](https://cloud.githubusercontent.com/assets/7126237/22741836/df7b166c-ee14-11e6-8099-42d48dac01eb.png)
![connect_github](https://cloud.githubusercontent.com/assets/7126237/22741833/df76049c-ee14-11e6-9839-3a7190ed3122.png)
![create_new](https://cloud.githubusercontent.com/assets/7126237/22741835/df7864c6-ee14-11e6-8b88-2991b558c4eb.png)
![env_vars](https://cloud.githubusercontent.com/assets/7126237/22741834/df7850c6-ee14-11e6-9ae1-b344adcebecf.png)
![phoenix_app](https://cloud.githubusercontent.com/assets/7126237/22741837/df82d7c6-ee14-11e6-9a3f-2d16c28e729b.png)

**Comment by nelsonic** [comment]
PR for these sceenshots has been merged so closing. 👍
