### ISSUE TITLE
Trying to execute a single ExUnit test

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-phoenix-framework#34]
Tried using the code in the book on p.131. (_copied verbatim_):
```
defmodule MyTest do
  use ExUnit.Case, async: true

  setup do
    # run some tedious setup code
    :ok
  end

  test "pass" do
    assert true
  end

  test "fail" do
    assert false
  end
end
```
tried to run the _individual_ file in the terminal.

But got the following error:
```
(RuntimeError) cannot use ExUnit.Case without starting the ExUnit application, please call ExUnit.start() or explicitly start the :ex_unit app
```
Screenshot:
![image](https://cloud.githubusercontent.com/assets/194400/23098684/b0f34252-f64c-11e6-87fa-c6cdaff5b5a9.png)

Looked at https://hexdocs.pm/ex_unit/ExUnit.Case.html but no luck. 
Also looked at https://elixirschool.com/lessons/basics/testing and didn't get much enlightenment...

I'm trying to execute a _single_ test file ...
looked at: http://stackoverflow.com/questions/26150146/how-can-i-make-mix-run-only-specific-tests-from-my-suite-of-tests
Tried `mix test basic-test.exs` and `mix test --only basic-test.exs`
![image](https://cloud.githubusercontent.com/assets/194400/23098835/5aa70916-f650-11e6-9ad5-22be8cc096e6.png)

This question _might_ be more appropriate in https://github.com/dwyl/learn-elixir ...
but I figured that given its from the "Programming Phoenix" book, other people might _find_ it here....

**Comment by nelsonic** [comment]
Didn't _succeed_ in running the single test. (_decided to move on with the Phoenix tutorial ..._)
But would _still_ like to know if/how to do it if anyone `else` fiugres it out.
if you know how to run a single test file, please share/comment. thanks! 👍

**Comment by shouston3** [comment]
I managed to run tests by following [this](http://elixir-lang.org/getting-started/mix-otp/introduction-to-mix.html#running-tests)

You need to create a `test_helper.exs` file (these are generated automatically when running `mix new .`) which includes the `ExUnit.start()` script

To get a single test running do the following:

```
cd Desktop
mix new testing
cd testing
touch test/basic-test.exs
```

paste the above into that file

Then run:

`mix test test/basic-test.exs`

And it should work

**Comment by nelsonic** [comment]
@shouston3 yeah, I should have _clarified_ that I was trying to _avoid_ creating a new project using `mix` but you're _right_, that's the _simplest_ way of making progress with this. 👍  
(_thanks for being on-the-ball and taking the time to reply. hope you're having a good weekend._)

**Comment by shouston3** [comment]
In that case you could run:

```
elixir -e "ExUnit.start()" -r basic-test.exs
```

**Comment by shouston3** [comment]
@nelsonic happy for you to close this 👍

**Comment by nelsonic** [comment]
@shouston3 my next PR will close it. 👍
