### ISSUE TITLE
...warning: `Ecto.Changeset.cast/4` is deprecated, please use `cast/3` + `validate_required/3` instead

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-phoenix-framework#35]
running `mix test` on page 134
but get the following warning message:
```
...warning: `Ecto.Changeset.cast/4` is deprecated, please use `cast/3` + `validate_required/3` instead
    (rumbl) web/models/video.ex:22: Rumbl.Video.changeset/2
    test/models/video_test.exs:15: Rumbl.VideoTest."test changeset with invalid attributes"/1
    (ex_unit) lib/ex_unit/runner.ex:296: ExUnit.Runner.exec_test/1
    (stdlib) timer.erl:166: :timer.tc/1

.warning: `Ecto.Changeset.cast/4` is deprecated, please use `cast/3` + `validate_required/3` instead
    (rumbl) web/models/video.ex:22: Rumbl.Video.changeset/2
    test/models/video_test.exs:10: Rumbl.VideoTest."test changeset with valid attributes"/1
    (ex_unit) lib/ex_unit/runner.ex:296: ExUnit.Runner.exec_test/1
    (stdlib) timer.erl:166: :timer.tc/1
```

![image](https://cloud.githubusercontent.com/assets/194400/23101425/2c747214-f68b-11e6-83c0-2aae2b79d2d9.png)

Looked at: https://hexdocs.pm/ecto/Ecto.Changeset.html

tried changing the code in `web/models/video.ex:20-25` from:
```elixir
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, @required_fields, @optional_fields)
    |> assoc_constraint(:category)
  end
```

To:
```elixir
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, @optional_fields)
    |> validate_required(params, @required_fields)
    |> assoc_constraint(:category)
  end
```
or:
```elixir
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [@required_fields, @optional_fields]) # cast all fields as a single list
    |> validate_required(params, @required_fields)
    |> assoc_constraint(:category)
  end
```
but tests failed:
![image](https://cloud.githubusercontent.com/assets/194400/23101630/e3986988-f68f-11e6-98f1-69ecf5675874.png)

figured I need to call `cast` on _all_ the fields as a _single_ list.
read http://learningwithjb.com/posts/concat-lists-with-elixir
So changed to:
```elixir
  @required_fields ~w(url title description)
  @optional_fields ~w(category_id)
  @all_fields ~w(url title description category_id) # obviously not "DRY"

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, @all_fields)
    |> validate_required(@required_fields)
    |> assoc_constraint(:category)
  end
```
and ran: `mix test` and got:
![test fail](https://cloud.githubusercontent.com/assets/194400/23102024/4eaf02aa-f699-11e6-89aa-15baa8aa873e.png)

I would _like_ to `continue` spending time on this but I _suspect_ that it will become clear to me later in the book or through more practice/understanding so I'm just going to leave this issue open in `case` someone `else` knows how to "_fix_" it ...

**Comment by shouston3** [comment]
@nelsonic I may be totally off the mark, but what happens if you change:

```
|> validate_required(params, @required_fields)
```

to

```
|> validate_required(@required_fields)
```

I tried something similar to that and it seemed to work (I'm not as far through the book as you so I can't run the example you are running just yet).

**Comment by Jbarget** [comment]
For anyone following "Programming Pheonix" around page 60:

@des-des and I were running into the same warnings and ended up doing the below

```elixir
  def changeset(model, params \\ :invalid) do
    model
    |> cast(params, ~w(name username))
    |> validate_required([:name, :username])
    |> validate_length(:username, min: 1, max: 20)
  end
```

`params` is injected as the first argument to `validate_required`

**Comment by untra** [comment]
I would add to that: the book adds a uniqueness index to the `username` field, but doesn't suggest a way to validate that uniqueness:
```elixir
 def changeset(model, params \\ :invalid) do
    model
    |> cast(params, ~w(name username))
    |> validate_required([:name, :username])
    |> unique_constraint(:username)
    |> validate_length(:username, min: 1, max: 20)
  end
```
I would recommend also adding the `|> unique_constraint(:username)` to the username validations

**Comment by nelsonic** [comment]
@untra thanks for sharing. I have a _slight_ variation on this:
```
 def changeset(model, params \\ :invalid) do
    model
    |> cast(params, ~w(name username))
    |> validate_required([:name, :username])
    |> validate_length(:username, min: 1, max: 20)
    |> unique_constraint(:username) # save the unique_constraint for last as it "hits" the DB. ;-)
  end
```
