### ISSUE TITLE
tests failing in rumbl/test/models/user_test.exs

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-phoenix-framework#41]
on p.150 when attempting to run `mix test test/models/user_test.exs`

![image](https://cloud.githubusercontent.com/assets/194400/23345110/983bdf96-fc80-11e6-8599-88d956c10425.png)

unclear why ...

**Comment by nelsonic** [comment]
On investigation of the Errata https://pragprog.com/titles/phoenix/errata
![p.150 errata](https://cloud.githubusercontent.com/assets/194400/23345141/fd33d138-fc80-11e6-8266-c2f433743182.png)

**Comment by nelsonic** [comment]
change:
```
  test "changeset does not accept long usernames" do
    attrs = Map.put(@valid_attrs, :username, String.duplicate("a", 30))
    assert {:username, {"should be at most %{count} character(s)", [count: 20]}} in
      errors_on(%User{}, attrs)
  end
```
to:
```
  test "changeset does not accept long usernames" do
    attrs = Map.put(@valid_attrs, :username, String.duplicate("a", 30))
    assert username: "should be at most 20 character(s)" in
      errors_on(%User{}, attrs)
  end
```

**Comment by nelsonic** [comment]
totes works with the change. closing.

**Comment by bekapod** [comment]
Was this a bug/typo or is it something that has been removed from elixir?

**Comment by nelsonic** [comment]
@bekapod a typo. 🙄
