### ISSUE TITLE
Changeset validation (page 67)

### ISSUE THREAD

**Issue by Jbarget** [dwyl/learn-phoenix-framework#47]
Just messing around with the changeset validation outlined in the Programming Phoenix, page 67:

```elixir
  def changeset(model, params \\ :invalid) do
    model
    |> cast(params, ~w(name username))
    |> validate_required([:username], message: "username cannot be left empty")
    |> validate_required([:name], message: "name cannot be left empty")
    |> validate_length(:username, min: 1, max: 20)
  end
```

The above works perfectly. However if we comment out this line:
`# |> validate_required([:username], message: "username cannot be left empty")`

then we get an error from the database that username is null even though we've set minimum characters to 1.
![screen shot 2017-03-03 at 19 54 38](https://cloud.githubusercontent.com/assets/11725595/23562690/2f2def2e-004c-11e7-97fe-ec9b174d313a.png)

Any ideas? @nelsonic @shouston3 @jackcarlisle @katbow

**Comment by jackcarlisle** [comment]
@Jbarget can you post an example of the model and params that you're testing it with?

**Comment by Jbarget** [comment]
this is the full model:

```elixir
defmodule Rumbl.User do
  use Rumbl.Web, :model

  schema "users" do
    field :name, :string
    field :username, :string
    field :password, :string, virtual: true
    field :password_hash, :string

    timestamps()
  end
  def changeset(model, params \\ :invalid) do
    model
    |> cast(params, ~w(name username))
    # |> validate_required([:username], message: "username cannot be left empty")
    |> validate_required([:name], message: "name cannot be left empty")
    |> validate_length(:username, min: 1, max: 20)
  end
end
```

params: 

we submit a form with the name filled in and an empty username

```elixir
{
  name: 'jbarget'
  username: (not sure if this is an empty string or null or undefined, not used to what elixir's default values are) 
}
```

**Comment by katbow** [comment]
If username is not filled in, then there wouldn't be a `username` field in the changeset. There is nothing to check the length of, so the `validate_length` is not run.

In the changeset you will have a map called `changes`. It would look something like this if you only fill in the name and there is no username:
```ex
changes: %{name: "jbarget"}
``` 

`validate_required` ensures that `username` is in the changes map, so it doesn't go to the database with a null value. `validate_length` only checks the length if it's present. 👍

**Comment by Jbarget** [comment]
thanks @katbow! makes sense
