### ISSUE TITLE
p.165 when attempting to run "mix ecto.migrate" getting error: (Postgrex.Error) ERROR 42P07 (duplicate_table): relation "videos" already exists

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-phoenix-framework#50]
![image](https://cloud.githubusercontent.com/assets/194400/23585951/d7d3e00c-0182-11e7-8508-a8abcbb07acd.png)

```
nelson@local:rumbl Admin$ mix ecto.migrate

09:04:00.993 [info]  == Running Rumbl.Repo.Migrations.CreateVideo.change/0 forward

09:04:00.993 [info]  create table videos
** (Postgrex.Error) ERROR 42P07 (duplicate_table): relation "videos" already exists
    (ecto) lib/ecto/adapters/sql.ex:195: Ecto.Adapters.SQL.query!/5
    (ecto) lib/ecto/adapters/postgres.ex:86: anonymous fn/4 in Ecto.Adapters.Postgres.execute_ddl/3
    (elixir) lib/enum.ex:1623: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto) lib/ecto/adapters/postgres.ex:86: Ecto.Adapters.Postgres.execute_ddl/3
    (ecto) lib/ecto/migration/runner.ex:98: anonymous fn/2 in Ecto.Migration.Runner.flush/0
    (elixir) lib/enum.ex:1623: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto) lib/ecto/migration/runner.ex:96: Ecto.Migration.Runner.flush/0
    (stdlib) timer.erl:181: :timer.tc/2
    (ecto) lib/ecto/migration/runner.ex:27: Ecto.Migration.Runner.run/6
    (ecto) lib/ecto/migrator.ex:121: Ecto.Migrator.attempt/6
    (ecto) lib/ecto/migrator.ex:71: anonymous fn/4 in Ecto.Migrator.do_up/4
    (ecto) lib/ecto/adapters/sql.ex:615: anonymous fn/3 in Ecto.Adapters.SQL.do_transaction/3
    (db_connection) lib/db_connection.ex:1274: DBConnection.transaction_run/4
    (db_connection) lib/db_connection.ex:1198: DBConnection.run_begin/3
    (db_connection) lib/db_connection.ex:789: DBConnection.transaction/3
    (ecto) lib/ecto/migrator.ex:244: anonymous fn/4 in Ecto.Migrator.migrate/4
    (elixir) lib/enum.ex:1184: Enum."-map/2-lists^map/1-0-"/2
    (ecto) lib/mix/tasks/ecto.migrate.ex:84: anonymous fn/4 in Mix.Tasks.Ecto.Migrate.run/2
    (elixir) lib/enum.ex:651: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:651: Enum.each/2
```

**Comment by nelsonic** [comment]
Out of _impatience_ I deleted all tables in the database!
and then the `mix ecto.migrate` worked:
![image](https://cloud.githubusercontent.com/assets/194400/23586046/367fdba4-0185-11e7-8bef-0c14cdda3b28.png)

When I ran `mix test` I got:
![image](https://cloud.githubusercontent.com/assets/194400/23586083/d2d9fb88-0185-11e7-8169-329d1f33bb1a.png)

there are (_were_) two `_create_video.exs` migrations:
![image](https://cloud.githubusercontent.com/assets/194400/23586071/adcbad50-0185-11e7-8f27-de3a8c97235a.png)
So I deleted one of them. 

The migration works but getting an error `ERROR 42P07 (duplicate_table): relation "videos" already exists` when attempting to run the tests:
![image](https://cloud.githubusercontent.com/assets/194400/23586089/fae36f10-0185-11e7-85ff-fc5920f786c1.png)

**Comment by nelsonic** [comment]
This is an _exceptionally_ frustrating error message because the **debug log is _utterly_ useless**!! 😢

**Comment by nelsonic** [comment]
"solved" it by deleting all tables in the `rumbl_test` database and re-running `mix test`:
at least now the tests _run_ but one of them is failing:

![image](https://cloud.githubusercontent.com/assets/194400/23586131/2798132a-0187-11e7-962a-1bacf85366e6.png)

**Comment by jackcarlisle** [comment]
This might have been an issue to do with not "rolling back" your duplicate migration. If you want to undo a migration you can call `mix ecto.rollback` which will completely remove it. You can also roll back to specific migrations using: 

`mix ecto.rollback -v [timestamp]`

**Comment by nelsonic** [comment]
Googlededed for the error: `no function clause matching in Ecto.build_assoc/3`
foundeded: https://elixirforum.com/t/no-function-clause-matching-in-ecto-build-assoc-3/1123

**Comment by nelsonic** [comment]
After a bit of digging found the answer on: https://forums.pragprog.com/forums/393/topics/14291
duplicate `resources "/videos", VideoController` in `scope "/"` and `scope "/manage"` of `router.ex`
