### ISSUE TITLE
Ecto testing 100% Coverage

### ISSUE THREAD

**Issue by shouston3** [dwyl/learn-phoenix-framework#55]
When striving to get 100% coverage, the schema line sometimes fails
![screen shot 2017-03-06 at 16 30 21](https://cloud.githubusercontent.com/assets/15983736/23619872/fd89b064-028c-11e7-80d1-b9f74dbd5d89.png)

I have found this line in your models test impossible to consistently cover (without ignoring the file from coverage)

See the progression of the problem in our application here: https://github.com/InclusiveClassrooms/skills-wheel/issues/63

**Comment by nelsonic** [comment]
@shouston3 thanks for investigating this (_and sharing your findings!_) 👍

**Comment by shouston3** [comment]
Unable to replicate this bug any more. A solution would probably now found through using `excoveralls` [Stop Words](https://github.com/parroty/excoveralls#stop-words)

Adding this to ones `coveralls.json` file may have fixed the bug:
```json
  ...

  "default_stop_words": [
    "schema"
  ],

```

Phoenix also doesn't have `models` any more so even less relevant, closing
