### ISSUE TITLE
secret_key on Heroku

### ISSUE THREAD

**Issue by SimonLab** [dwyl/learn-phoenix-framework#56]
I think we should try to avoid using the secret_key from the config.exs file as this file is not it gitignore by default so anyone can have access to the key. see https://github.com/dwyl/learn-phoenix-framework/blame/master/heroku-deployment.md#L111

Instead we should try to create a new key with ```mix phoenix.gen.secret```

**Comment by jruts** [comment]
Hey @SimonLab , the secret key is being fetched from an environment variable `secret_key_base: System.get_env("SECRET_KEY_BASE")`; so you would not check that into github anyway. How would anyone be able to access it?

**Comment by SimonLab** [comment]
Yes, sorry I misread your comment and forget to update the config.exs with the Heroku environment variable. Everything is good :+1:
