### ISSUE TITLE
Fix typos, add missing steps and change example for sending emails

### ISSUE THREAD

**Issue by katbow** [dwyl/learn-phoenix-framework#62]
Going through the [sending email README](https://github.com/dwyl/learn-phoenix-framework/blob/master/sending-emails.md), I noticed a few typos/grammatical errors which needed fixing. 

I also thought the example would be better updated to a more realistic use case - inputting the subject and message you would send instead of inputting emails (which can only be to/from emails you have previously verified).

If someone can verify this, I can make a PR for it @shouston3 🙂

**Comment by nelsonic** [comment]
@katbow please go for it! typo/grammar fixes are _always_ welcome! 👍
