### ISSUE TITLE
How can i install Phoenix? 

### ISSUE THREAD

**Issue by edwardcodes** [dwyl/learn-phoenix-framework#74]
Just starting reading through the dwyl tutorial but i can´t find instructions on how to install Phoenix...

**Comment by nelsonic** [comment]
@edwardcodes good question. please try: http://www.phoenixframework.org/docs/installation

**Comment by iteles** [comment]
We should go ahead and add this to the readme...!

**Comment by nelsonic** [comment]
Yes. 👍

**Comment by ZooeyMiller** [comment]
I've not got the appropriate rights to assign this to myself but this is in progress, working on a PR to add this in now (T25m)
