### ISSUE TITLE
When isn't Phoenix useful for an Elixir application?

### ISSUE THREAD

**Issue by Cleop** [dwyl/learn-phoenix-framework#81]
Given the speedy and comprehensive set up that phoenix offers, when is it not useful/necessary to use phoenix on an elixir application?

Once I know a framework I tend to use it by default when setting up a project, on what occasions might I want to consider _not_ doing this?

**The question came from this comment by @nelsonic :**
https://github.com/dwyl/tachyons-bootstrap/pull/10#pullrequestreview-39681879
![image](https://cloud.githubusercontent.com/assets/16775804/26347774/7dec9fc6-3fa2-11e7-8d3d-996d6842e5cb.png)

**Comment by nelsonic** [comment]
@Cleop in the context of `tachyons-bootstrap` the idea would be to _focus_ on the `tachyons` part, not to add Elixir & Phoenix as _pre-requisites_ `before` people can use the code snippets.
I should have made that _clearerer_ but in this issue: https://github.com/dwyl/learn-tachyons/issues/8 I demo how to re-create bootstrap with _just_ HTML. 
The way I _envisioned_ this project was _super-simple_ file structure e.g:
```
index.html            // basic layout template where all components would be displayed
component_order.txt   // line-separated list of all the components in the order they appear
component_combiner.js // a *super basic* node.js (_core-only_) script combines the components
/components
  button.html
  form.html
  etc ...
package.json          // http-server dependency to deploy to heroku + test script for CI
.travis.yml           // build so we can check it's still working when others contribute.
```
This way it's not "_intimidating_" to beginner _contributors_ who might be "_put off_" by Elixir/Phoenix.

To be clear I don't think Elixir is a _requirement_ for the `tachyons-bootstrap` project.
In terms of the "_advanced-ness_" (_it's not a word but bare with me_) of the example, 
we can keep them _way_ more beginner-friendly with _way_ fewer lines of "_boilerplate_" (_detest that word! but it is applicable here_) code and folders. A "_standard_" Phoneix project has a _lot_ of "_noise_":
![image](https://cloud.githubusercontent.com/assets/194400/26352880/a678dfc8-3fb5-11e7-9bde-ec23a26c4d06.png)

To a _beginner_ this folder structure is "Whaaat...?"
![image](https://cloud.githubusercontent.com/assets/194400/26353055/4e5cf954-3fb6-11e7-83c1-e5091ce7d9e8.png)

Unless there is a _significant_ benefit from using Elixir/Phoenix I would stick to HTML+JS for these _simpler_ examples.

**Comment by Cleop** [comment]
Great, thank you @nelsonic this makes so much sense.

I think I assumed based on the scripting idea from LDMW that this was the line we were going down as I thought that was a test run for tachyons-bootstrap.

Thanks for sharing your more basic example structure, I didn't realise we could achieve everything we wanted with such a stripped down version but it's great to see you can. Simplicity is often best!

**Comment by Cleop** [comment]
@nelsonic - could you share the repo which you gave the example file structure for? I'd like to explore the folders more.
