### ISSUE TITLE
Forgotten Password Flow

### ISSUE THREAD

**Issue by katbow** [dwyl/learn-phoenix-framework#86]
While there are [libraries](https://github.com/smpallen99/coherence) to help with the forgotten password flow, they require set up from the start. They need to be used for authentication before being able to use them for forgotten password.

If you set up your own auth plug, or used a different library that doesn't offer forgotten password, you may need to make your own controller/flow for forgotten passwords.

Layout how to make your own ForgottenPasswordController.

**Comment by nelsonic** [comment]
@katbow added a _superb_ writeup of this: https://github.com/dwyl/learn-phoenix-framework/blob/master/forgot-password.md
Closing.
