### ISSUE TITLE
How to run localhost in browser when connected to VM via ssh

### ISSUE THREAD

**Issue by katbow** [dwyl/learn-phoenix-framework#92]
We are running our phoenix application in a virtual machine. We had some trouble getting this started, and found out we need to run it as
`sudo mix phoenix.server` instead of just `mix phoenix.server`.

We can make requests with `curl` and see the response from the server, however we have not been able to figure out how to go to localhost to view the changes to the site from here & check if it runs as expected.

We tried going to the IP address that we ssh'd into with `:4000` and it just hung. 

Need this for checking https://github.com/healthlocker/healthlocker/issues/852

**Comment by nelsonic** [comment]
@katbow did you see: 
https://github.com/dwyl/learn-phoenix-framework/blob/master/production-deployment.md#redirect-tcp-port-80-to-port-4000-where-our-app-is-listening ? 🤔

**Comment by katbow** [comment]
@nelsonic thanks! That works a charm ✨ 💃

**Comment by nelsonic** [comment]
@katbow please `close` if answered. 😉

**Comment by katbow** [comment]
yep, all good. thanks again 🙂
