### ISSUE TITLE
dpkg not found

### ISSUE THREAD

**Issue by hariharasudhan94** [dwyl/learn-phoenix-framework#96]
when i am following this tuto on [https://github.com/dwyl/learn-phoenix-framework/blob/master/production-deployment.md#161-install-build-tools-on-the-virtual-machine](url) i am getting error like 

> bash: dpkg: command not found

i am using fedora. how to install erlang solutions?

**Comment by nelsonic** [comment]
https://unix.stackexchange.com/a/256299/148453
