### ISSUE TITLE
failed: Error during WebSocket handshake: Unexpected response code: 403

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-phoenix-framework#99]
while _trying_ to get Phoenix to work behind an NGINX Proxy, we are getting the error:
```
WebSocket connection to 'wss://staging.healthlocker.uk/socket/websocket?token=SFMyNTY.g3QAAAACZAAEZG…c2lnbmVkbgYALXOTYF0B.V1vd7-z376dGRNdJWuMsS5iFI5ibkjPDvZiCadCuIxU&vsn=1.0.0' 
failed: Error during WebSocket handshake: Unexpected response code: 403
```
![image](https://user-images.githubusercontent.com/194400/28425146-578f566e-6d67-11e7-9049-c1c37ebe5017.png)

The firfox equivalent error is:
```
Firefox can't establish a connection to the server at 
wss://staging.healthlocker.uk/socket/websocket?token=SFMyNTY.g3QAAAACZAAEZGF0YWEiZAAGc2lnbmVkbgYAP2SWYF0B.5xlE8wqmMRcNovNy9Ux1etX5S2wgDWLn5Vs2m0EylLk&vsn=1.0.0.
```
![image](https://user-images.githubusercontent.com/194400/28425256-9ae63d2e-6d67-11e7-8817-1ce422424d20.png)

Fairly certain someone `else` will encounter this issue, so I'm recording it here so that when I figure it out, the solution will appear for them in Google SERPs! 👍 
relates to: #98 and https://github.com/healthlocker/healthlocker/issues/387

**Comment by nelsonic** [comment]
This nginx config is _very_ similar to what I have: https://forums.meteor.com/t/how-do-you-fix-websocket-error/2827/9
![image](https://user-images.githubusercontent.com/194400/28427608-ac9b82ac-6d6e-11e7-84ec-49b84b526294.png)
sadly, after going through it line-by-line it has no effect. 😞

**Comment by nelsonic** [comment]
Found: https://github.com/drone/drone/issues/767
which suggests: 
```
proxy_set_header Origin '';
```
Works!
![image](https://user-images.githubusercontent.com/194400/28427929-9cc7117e-6d6f-11e7-95d8-bceb883f2cad.png)

**Comment by nelsonic** [comment]
Works. everyone's happy again. https://github.com/healthlocker/healthlocker/issues/915

**Comment by reddog** [comment]
Does this Phoenix issue shed more light on to what is/isn't working and why?  https://github.com/phoenixframework/phoenix/issues/1359

Would this Phoenix config setting remove the need for the nginx config change (which could be why the Phoenix examples themselves work without the `Origin` line?):  https://github.com/phoenixframework/phoenix/issues/1359#issuecomment-168761849

`check_origin: false`

**Comment by nelsonic** [comment]
@reddog indeed applying the setting in the Phoenix `prod.exs` _would_ be another approach to solving the issue. 👍

**Comment by jayjun** [comment]
@nelsonic @reddog `check_origin: false` opens your site up for Cross-Site WebSocket Hijacking (CSWSH) attacks. This setting is for development environments, or if the domain served is truly unknown and you are willing to accept the security tradeoff.

Guessing from your screenshot, your setting should be

```elixir
check_origin: ["//healthlocker.uk", "//staging.healthlocker.uk"]
```

Read https://www.christian-schneider.net/CrossSiteWebSocketHijacking.html for details.

**Comment by nelsonic** [comment]
@jayjun thanks for sharing the link. 👍
